version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql
    restart: always
    volumes:
      - feelibrary-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feelibrary
      MYSQL_USER: feelibrary
      MYSQL_PASSWORD: feelibrary
      
volumes:
  feelibrary-mysql-data:
