version: "3"

services:
  # api:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #     target: development
  #   volumes:
  #     - .:/usr/src/app
  #   # command: ["npm", "run", "start:dev"]
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - database

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - feelibrary-mysql-data:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

volumes:
  feelibrary-mysql-data:
